# Generated by Django 5.2 on 2025-04-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_chat_entry_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emoji_level',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='light', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tone',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('stoic', 'Stoic'), ('very honest', 'Very Honest'), ('sweet', 'Sweet'), ('dry', 'Dry')], default='friendly', max_length=100),
        ),
    ]
