# Generated by Django 5.2 on 2025-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profile_emoji_level_alter_profile_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='entries',
            field=models.ManyToManyField(to='main_app.entry'),
        ),
    ]
