# Generated by Django 5.2 on 2025-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_entry_chat_chat_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prompt',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
