# Generated by Django 5.2 on 2025-04-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_entry_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emoji_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tone',
        ),
        migrations.AddField(
            model_name='entry',
            name='emoji_level',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='light', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='tone',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('stoic', 'Stoic'), ('very honest', 'Very Honest'), ('sweet', 'Sweet'), ('dry', 'Dry')], default='friendly', max_length=100),
        ),
    ]
