# Generated by Django 5.2 on 2025-04-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_chat_emoji_level_chat_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
        migrations.AddField(
            model_name='chat',
            name='initial_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
